name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Modulo1-clases y objetos
      id: modulo1-clases-y-objetos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Modulo1-clases y objetos
        setup-command: ''
        command: listo
        timeout: 60
        max-score: 10
    - name: Modulo2
      id: modulo2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Modulo2
        setup-command: ''
        command: Listo
        timeout: 60
        max-score: 10
    - name: Modulo3
      id: modulo3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Modulo3
        setup-command: ''
        command: Listo
        timeout: 60
        max-score: 10
    - name: Modulo4
      id: modulo4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Modulo4
        setup-command: ''
        command: make test
        timeout: 60
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MODULO1-CLASES-Y-OBJETOS_RESULTS: "${{steps.modulo1-clases-y-objetos.outputs.result}}"
        MODULO2_RESULTS: "${{steps.modulo2.outputs.result}}"
        MODULO3_RESULTS: "${{steps.modulo3.outputs.result}}"
        MODULO4_RESULTS: "${{steps.modulo4.outputs.result}}"
      with:
        runners: modulo1-clases-y-objetos,modulo2,modulo3,modulo4
